AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: edu.ucsf.library.idl.bulkdl.ZipUploadRequestHandler::handleRequest
      FunctionName: bulkdl
      Timeout: 60
      MemorySize: 512
      CodeUri: ./target/idl-bulkdl.jar
      Environment:
        Variables:
          AWS_ACCESS_KEY_ID:
          AWS_SECRET_ACCESS_KEY:
          AWS_REGION:
          IDL_BULKDL_BUCKET_SOURCE:
          IDL_BULKDL_BUCKET_TARGET:
      Policies:
        - S3ReadPolicy:
            BucketName: oida-test-data
        - S3FullAccessPolicy:
            BucketName: oida-test-bulkdl