AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      Handler: edu.ucsf.library.idl.bulkdl.ZipUploadRequestHandler::handleRequest
      FunctionName: bulkdl
      Timeout: 900
      MemorySize: 512
      CodeUri: ./target/idl-bulkdl.jar
      Environment:
        Variables:
          IDL_BULKDL_BUCKET_SOURCE: oida-test-data
          IDL_BULKDL_BUCKET_TARGET: oida-test-bulkdl
          IDL_BULKDL_BUFFER_SIZE: 10485760
      Policies:
        - S3ReadPolicy:
            BucketName: oida-test-data
        - S3FullAccessPolicy:
            BucketName: oida-test-bulkdl